### ISSUE TITLE
Chem4Word Inactive

### ISSUE THREAD

**Issue by cramerps** [Chem4Word/Version3#2]
Greetings

I Installed C4W and received no install errors.  However, when word is launched the menu is entirely grayed out  with the exception of the Options & Help buttons. De-activating and re-activating the add-in has no effect.  I uninstalled and reinstalled also with no effect. I rebooted the machine with no effect.  Attached is the install log

[2018-02-15.log](https://github.com/Chem4Word/Version3/files/1729009/2018-02-15.log)

I also installed C4W on a duplicate set of hardware with no difficulties.

The machines in question are both Dell T7500, Dual Xeon, 12Gb Ram running Win7-Pro-64.

Thoughts on what to do?

Sincerely Paul

**Comment by cramerps** [comment]
Ah, But not all older documents?  A puzzlement?

Paul

**Comment by cramerps** [comment]
Here is an empty document that exhibits the problem.

Paul
[The Problem.docx](https://github.com/Chem4Word/Version3/files/1729090/The.Problem.docx)

**Comment by cramerps** [comment]
Here is the problem doc with a C4W structure copy and pasted in and saved.  Even afterwards you cannot add new structures or modify existing ones.

Paul

[The Problem 2.docx](https://github.com/Chem4Word/Version3/files/1729114/The.Problem.2.docx)

**Comment by cramerps** [comment]
Greetings

The document was in 2016 format but running in compatibility mode.  Converting fixed the problem.

Paul

**Comment by MikeWilliams-UK** [comment]
Hi,

I was just about to reply with the note about compatability mode.
During development we found out that a document must NOT be in compatabity
mode otherwise SOME of the functions we use don't work.

We therefore made the decision to disable the active buttons if the
document is in compatablity mode.
I think there may still be loophole in our detection of this, which may
have led to extra confusion.

This was publicised to the our FaceBook group, maybe you missed this
notification.

**Comment by MikeWilliams-UK** [comment]
Hi Paul,

I have further examined the supplied documents and I can see that the second document has a partial copy of the structure, which can never be editable due to missing information [that which is incompatible with older documents]. Only the picture has been copied, the cml [xml] was not copied.

/Mike

**Comment by cramerps** [comment]
Mike

Thanks for the reply, thought I did puzzle it out eventually.  There was
however, no FAQ about it and must admit I did not look in Facebook (I
simply don't have much use for it ;-)

I did notice a couple of other interesting issues.  If a structure is
placed in a table the majority of table functions are disabled.  For
instance you cannot adjust centering or font type and color for the entire
table.  If the structure is cut out, the table changed and the structure
pasted back in all is well.

The structures can also not be resized and no drag handles appear on the
graphic.  I do not know if this is intended functionality or not.  IF the
"remove Content Controls" is selected the graphic is realizable but looses
its connection to C4W.

Also no formatting can be performed on the image, outline, shadow etc.
These are often valuable when making "pretty pictures" for management who
enjoy their colored pictures above content ;-)

But many thanks its an excellent program  and I did not have an opportunity
to use it for some time but it has improved greatly.  Many thanks.

Paul

**Comment by MikeWilliams-UK** [comment]
Hi Paul,

The issue with tables is nothing of our doing. If you add a rich text
content control in a table, then lock it's contents, the exact same
behaviour is exhibited. It seems to affect table operations and cell
operations, but cell operations on other cells are possible. One trick we
tried that  seemed to work was to insert a space before the chemistry
object, this tricks the table into working normally (most of the time).
This been reported to the Microsoft Word team, but as it has been present
since Word 2010 we don't expect them to resolve what they probably consider
a bug which only affects a very small percentage of Word users.

I will get this and the [must not be in] compatibility mode requirement
noted in the next version of the manual.

We lock the contents to discourage people from attempting to edit the
diagram (which consists of DrawingML objects) directly, so that they use
our drawing editor. As you have found out if you tamper with the drawing
you can easily disconnect if from the CML, which is stored in the document.

Within the editor you can also change the bond length to rescale the
drawing.

The font type is fixed at Arial, inside the drawing the characters are not
text. We have extracted the true type font curves and use them to give us
more precise control of their placement.

I have tried to get the drawing formatting tools to work via right click,
but to no avail.

/Mike

**Comment by cramerps** [comment]
Mike

Again many thanks.  I thought it would be something like that​.  What
little ive done with XML in Office documents has proven to be quite brittle
with respect to version change.

Have a good weekend.

Paul
